### Site metadata ###

site_name: Algoritmekader [concept]
site_description: Concept van het algoritmekader. Het doel daarvan is om overheden op praktische wijze te ondersteunen, zodat zij op een wettige en ethisch verantwoorde wijze algoritmes en AI-systemen gebruiken.
# watch:
#     - includes/

### theme settings ###
theme: 
    name: material
    language: nl
    palette:
        primary: blue
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.path
        - navigation.top
        - navigation.tracking
        # - navigation.footer
        - search.highlight
        - search.suggest
        - content.action.edit
    icon:
        logo: fontawesome/solid/house
        annotation: fontawesome/solid/circle-info

# Navigation for the site 
nav:
    - Home: index.md
    - Over het algoritmekader: 
        - overhetalgoritmekader/index.md
        - overhetalgoritmekader/definities.md
    - Levenscyclus:
        - levenscyclus/index.md 
        - levenscyclus/probleemanalyse.md
        - levenscyclus/ontwerp.md
        - levenscyclus/data verkenning en data preparatie.md
        - levenscyclus/ontwikkelen.md
        - levenscyclus/validatie.md
        - levenscyclus/implementatie.md
        - levenscyclus/monitoren.md
        - levenscyclus/archiveren.md
    - Bouwblokken:
        - bouwblokken/index.md
        - Conformiteitsbeoordeling:
            - bouwblokken/conformiteitsbeoordeling/index.md
            - bouwblokken/conformiteitsbeoordeling/audit.md
            - bouwblokken/conformiteitsbeoordeling/toezicht.md
        - Data:
            - bouwblokken/data/index.md
            - bouwblokken/data/data kwaliteit.md
            - bouwblokken/data/data governance.md
        - Duurzaamheid:
            - bouwblokken/duurzaamheid/index.md
        - Fundamentele rechten:
            - bouwblokken/fundamentele rechten/index.md
            - bouwblokken/fundamentele rechten/non-discriminatie.md
        - Governance:
          - bouwblokken/governance/index.md
        - Inkoop:
          - bouwblokken/inkoop/index.md
        - Menselijke controle:
          - bouwblokken/menselijke controle/index.md
        - Privacy en gegevensbescherming:
          - bouwblokken/privacy en gegevensbescherming/index.md
        - Technische robuustheid en veiligheid:
          - bouwblokken/technische robuustheid en veiligheid/index.md
        - Transparantie:
          - bouwblokken/transparantie/index.md
    - Normen:
        - normen/index.md
        - Conformiteitsbeoordeling:
           - normen/conformiteitsbeoordeling/index.md
           - normen/conformiteitsbeoordeling/norm1.md
        - Data:
           - normen/data/index.md
           - normen/data/norm1.md
        - Duurzaamheid:
           - normen/duurzaamheid/index.md
           - normen/duurzaamheid/norm1.md
           - normen/duurzaamheid/norm2.md
        - Fundamentele rechten:
           - normen/fundamentele rechten/index.md
           - normen/fundamentele rechten/norm1.md
        - Governance:
           - normen/governance/index.md
           - normen/governance/norm1.md
           - normen/governance/norm2.md
           - normen/governance/norm3.md
           - normen/governance/norm4.md
           - normen/governance/norm5.md
           - normen/governance/norm6.md
           - normen/governance/norm7.md
           - normen/governance/norm8.md
        - Inkoop:
           - normen/inkoop/index.md
           - normen/inkoop/norm1.md
        - Menselijke controle:
           - normen/menselijke controle/index.md
           - normen/menselijke controle/norm1.md
           - normen/menselijke controle/norm2.md
           - normen/menselijke controle/norm3.md
           - normen/menselijke controle/norm4.md
        - Privacy en gegevensbescherming:
           - normen/privacy en gegevensbescherming/index.md
           - normen/privacy en gegevensbescherming/norm1.md
           - normen/privacy en gegevensbescherming/norm2.md
           - normen/privacy en gegevensbescherming/norm3.md
           - normen/privacy en gegevensbescherming/norm4.md
           - normen/privacy en gegevensbescherming/norm5.md
           - normen/privacy en gegevensbescherming/norm6.md
           - normen/privacy en gegevensbescherming/norm7.md
           - normen/privacy en gegevensbescherming/norm8.md
           - normen/privacy en gegevensbescherming/norm9.md
           - normen/privacy en gegevensbescherming/norm10.md
           - normen/privacy en gegevensbescherming/norm11.md
           - normen/privacy en gegevensbescherming/norm12.md
        - Technische robuustheid en veiligheid:
           - normen/technische robuustheid en veiligheid/index.md
           - normen/technische robuustheid en veiligheid/norm1.md
           - normen/technische robuustheid en veiligheid/norm2.md
           - normen/technische robuustheid en veiligheid/norm3.md
           - normen/technische robuustheid en veiligheid/norm4.md
           - normen/technische robuustheid en veiligheid/norm5.md
           - normen/technische robuustheid en veiligheid/norm6.md
        - Transparantie:
           - normen/transparantie/index.md
           - normen/transparantie/norm1.md
           - normen/transparantie/norm2.md
           - normen/transparantie/norm3.md
           - normen/transparantie/norm4.md
           - normen/transparantie/norm5.md

    - Instrumenten: instrumenten/index.md

# Extra opties
markdown_extensions: 
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    - attr_list
    - abbr
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.snippets:
        auto_append:
            - includes/abbreviations.md

# Extra opties voor footer
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/MinBZK/Algoritmekader


plugins:
    - glightbox
    - search
    - git-revision-date-localized:
        enable_creation_date: true
    - tags:
        tags_hierarchy: true
        tags_file: tags.md

# Link naar GitHub repo (nu nog even mijn eigen repo)
repo_url: https://github.com/MinBZK/Algoritmekader
edit_uri: edit/main/docs/
